export type Exchange = "ADX" | "DFM";

export interface StockInfo {
  symbol: string;
  yahooSymbol: string;
  name: string;
  exchange: Exchange;
  sector: string;
}

export const ADX_STOCKS: StockInfo[] = [
  { symbol: "IHC", yahooSymbol: "IHC.AE", name: "International Holding Company PJSC", exchange: "ADX", sector: "Conglomerates" },
  { symbol: "TAQA", yahooSymbol: "TAQA.AE", name: "Abu Dhabi National Energy Company PJSC", exchange: "ADX", sector: "Energy" },
  { symbol: "ADNOCGAS", yahooSymbol: "ADNOCGAS.AE", name: "ADNOC Gas PLC", exchange: "ADX", sector: "Energy" },
  { symbol: "FAB", yahooSymbol: "FAB.AE", name: "First Abu Dhabi Bank P.J.S.C.", exchange: "ADX", sector: "Banking" },
  { symbol: "ETISALAT", yahooSymbol: "ETISALAT.AE", name: "Emirates Telecommunications Group Company PJSC", exchange: "ADX", sector: "Telecom" },
  { symbol: "ADCB", yahooSymbol: "ADCB.AE", name: "Abu Dhabi Commercial Bank PJSC", exchange: "ADX", sector: "Banking" },
  { symbol: "ADIB", yahooSymbol: "ADIB.AE", name: "Abu Dhabi Islamic Bank PJSC", exchange: "ADX", sector: "Banking" },
  { symbol: "ADNOCDIST", yahooSymbol: "ADNOCDIST.AE", name: "ADNOC Distribution PJSC", exchange: "ADX", sector: "Energy" },
  { symbol: "ADNOCDRILL", yahooSymbol: "ADNOCDRILL.AE", name: "ADNOC Drilling Company PJSC", exchange: "ADX", sector: "Energy" },
  { symbol: "ALPHADHABI", yahooSymbol: "ALPHADHABI.AE", name: "Alpha Dhabi Holding PJSC", exchange: "ADX", sector: "Conglomerates" },
  { symbol: "PRESIGHT", yahooSymbol: "PRESIGHT.AE", name: "Presight AI Holding PLC", exchange: "ADX", sector: "Technology" },
  { symbol: "ADNH", yahooSymbol: "ADNH.AE", name: "Abu Dhabi National Hotels P.J.S.C.", exchange: "ADX", sector: "Hospitality" },
  { symbol: "ADAVIATION", yahooSymbol: "ADAVIATION.AE", name: "Abu Dhabi Aviation Co.", exchange: "ADX", sector: "Aviation" },
  { symbol: "ADPORTS", yahooSymbol: "ADPORTS.AE", name: "AD Ports Group PJSC", exchange: "ADX", sector: "Logistics" },
  { symbol: "ALDAR", yahooSymbol: "ALDAR.AE", name: "Aldar Properties PJSC", exchange: "ADX", sector: "Real Estate" },
  { symbol: "FERTIGLOBE", yahooSymbol: "FERTIGLOBE.AE", name: "Fertiglobe PLC", exchange: "ADX", sector: "Chemicals" },
  { symbol: "MULTIPLY", yahooSymbol: "MULTIPLY.AE", name: "Multiply Group PJSC", exchange: "ADX", sector: "Conglomerates" },
  { symbol: "BOROUGE", yahooSymbol: "BOROUGE.AE", name: "Borouge PLC", exchange: "ADX", sector: "Chemicals" },
  { symbol: "PUREHEALTH", yahooSymbol: "PUREHEALTH.AE", name: "Pure Health Holding PJSC", exchange: "ADX", sector: "Healthcare" },
  { symbol: "BURJEEL", yahooSymbol: "BURJEEL.AE", name: "Burjeel Holdings PLC", exchange: "ADX", sector: "Healthcare" },
  { symbol: "INVESTB", yahooSymbol: "INVESTB.AE", name: "Invest Bank P.J.S.C.", exchange: "ADX", sector: "Banking" },
  { symbol: "QAHOLDING", yahooSymbol: "QAHOLDING.AE", name: "Q Holding PSC", exchange: "ADX", sector: "Conglomerates" },
  { symbol: "RAK", yahooSymbol: "RAK.AE", name: "RAK Bank P.J.S.C.", exchange: "ADX", sector: "Banking" },
  { symbol: "ADNIC", yahooSymbol: "ADNIC.AE", name: "Abu Dhabi National Insurance Company PJSC", exchange: "ADX", sector: "Insurance" },
  { symbol: "ORAS", yahooSymbol: "ORAS.AE", name: "Orascom Construction PLC", exchange: "ADX", sector: "Construction" },
  { symbol: "BOS", yahooSymbol: "BOS.AE", name: "Bank Of Sharjah P.J.S.C.", exchange: "ADX", sector: "Banking" },
  { symbol: "RAKPROP", yahooSymbol: "RAKPROP.AE", name: "RAK Properties PJSC", exchange: "ADX", sector: "Real Estate" },
  { symbol: "DRIVE", yahooSymbol: "DRIVE.AE", name: "Emirates Driving Company P.J.S.C.", exchange: "ADX", sector: "Services" },
  { symbol: "ESG", yahooSymbol: "ESG.AE", name: "ESG Emirates Stallions Group PJSC", exchange: "ADX", sector: "Conglomerates" },
  { symbol: "AGTHIA", yahooSymbol: "AGTHIA.AE", name: "Agthia Group PJSC", exchange: "ADX", sector: "Consumer Staples" },
  { symbol: "RAKCEC", yahooSymbol: "RAKCEC.AE", name: "R.A.K. Ceramics P.J.S.C.", exchange: "ADX", sector: "Industrial" },
  { symbol: "E7", yahooSymbol: "E7.AE", name: "E7 Group PJSC", exchange: "ADX", sector: "Conglomerates" },
  { symbol: "ASM", yahooSymbol: "ASM.AE", name: "Al Seer Marine Supplies and Equipment Company PJSC", exchange: "ADX", sector: "Industrial" },
  { symbol: "INVICTUS", yahooSymbol: "INVICTUS.AE", name: "Invictus Investment Company PLC", exchange: "ADX", sector: "Investment" },
  { symbol: "ADNHC", yahooSymbol: "ADNHC.AE", name: "ADNH Catering PLC", exchange: "ADX", sector: "Consumer Services" },
  { symbol: "ADSB", yahooSymbol: "ADSB.AE", name: "Abu Dhabi Ship Building PJSC", exchange: "ADX", sector: "Industrial" },
  { symbol: "CBI", yahooSymbol: "CBI.AE", name: "Commercial Bank International P.J.S.C.", exchange: "ADX", sector: "Banking" },
  { symbol: "GMPC", yahooSymbol: "GMPC.AE", name: "Gulf Medical Projects Company (PJSC)", exchange: "ADX", sector: "Healthcare" },
  { symbol: "ESHRAQ", yahooSymbol: "ESHRAQ.AE", name: "Eshraq Investments PJSC", exchange: "ADX", sector: "Real Estate" },
  { symbol: "JULPHAR", yahooSymbol: "JULPHAR.AE", name: "Gulf Pharmaceutical Industries P.S.C.", exchange: "ADX", sector: "Healthcare" },
  { symbol: "EIC", yahooSymbol: "EIC.AE", name: "Emirates Insurance Company P.J.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "PALMS", yahooSymbol: "PALMS.AE", name: "Palms Sports PJSC", exchange: "ADX", sector: "Consumer Services" },
  { symbol: "EASYLEASE", yahooSymbol: "EASYLEASE.AE", name: "Easy Lease Motor Cycle Rental P.S.C.", exchange: "ADX", sector: "Consumer Services" },
  { symbol: "MANAZEL", yahooSymbol: "MANAZEL.AE", name: "Manazel PJSC", exchange: "ADX", sector: "Real Estate" },
  { symbol: "ABNIC", yahooSymbol: "ABNIC.AE", name: "Al Buhaira National Insurance Company P.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "SCIDC", yahooSymbol: "SCIDC.AE", name: "Sharjah Cement and Industrial Development Co. (PJSC)", exchange: "ADX", sector: "Industrial" },
  { symbol: "AWNIC", yahooSymbol: "AWNIC.AE", name: "Al Wathba National Insurance Company PJSC", exchange: "ADX", sector: "Insurance" },
  { symbol: "QIC", yahooSymbol: "QIC.AE", name: "Umm Al Qaiwain General Investments Company P.S.C.", exchange: "ADX", sector: "Investment" },
  { symbol: "FH", yahooSymbol: "FH.AE", name: "Finance House P.J.S.C.", exchange: "ADX", sector: "Financial Services" },
  { symbol: "TKFL", yahooSymbol: "TKFL.AE", name: "Abu Dhabi National Takaful Company PSC", exchange: "ADX", sector: "Insurance" },
  { symbol: "DHAFRA", yahooSymbol: "DHAFRA.AE", name: "Al Dhafra Insurance Company P.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "RPM", yahooSymbol: "RPM.AE", name: "Response Plus Holding PJSC", exchange: "ADX", sector: "Healthcare" },
  { symbol: "ALAIN", yahooSymbol: "ALAIN.AE", name: "Al Ain Ahlia Insurance Company P.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "FNF", yahooSymbol: "FNF.AE", name: "Foodco National Foodstuff PJSC", exchange: "ADX", sector: "Consumer Staples" },
  { symbol: "BILDCO", yahooSymbol: "BILDCO.AE", name: "Abu Dhabi National Company for Building Materials PJSC", exchange: "ADX", sector: "Industrial" },
  { symbol: "GCEM", yahooSymbol: "GCEM.AE", name: "Gulf Cement Company P.S.C.", exchange: "ADX", sector: "Industrial" },
  { symbol: "FBI", yahooSymbol: "FBI.AE", name: "Fujairah Building Industries P.J.S.C.", exchange: "ADX", sector: "Industrial" },
  { symbol: "RAKNIC", yahooSymbol: "RAKNIC.AE", name: "Ras Al Khaimah National Insurance Company P.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "UNION", yahooSymbol: "UNION.AE", name: "Union Insurance Company P.J.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "HAYAH", yahooSymbol: "HAYAH.AE", name: "HAYAH Insurance Company P.J.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "SICO", yahooSymbol: "SICO.AE", name: "Sharjah Insurance Company P.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "ARAM", yahooSymbol: "ARAM.AE", name: "ARAM Group Company P.J.S.C.", exchange: "ADX", sector: "Industrial" },
  { symbol: "FCI", yahooSymbol: "FCI.AE", name: "Fujairah Cement Industries PJSC", exchange: "ADX", sector: "Industrial" },
  { symbol: "METHAQ", yahooSymbol: "METHAQ.AE", name: "Methaq Takaful Insurance P.S.C.", exchange: "ADX", sector: "Insurance" },
  { symbol: "ICAP", yahooSymbol: "ICAP.AE", name: "Investcorp Capital plc", exchange: "ADX", sector: "Financial Services" },
  { symbol: "ANAN", yahooSymbol: "ANAN.AE", name: "Anan Investment Holding PJSC", exchange: "ADX", sector: "Investment" },
  { symbol: "MAIR", yahooSymbol: "MAIR.AE", name: "MAIR Group - P.J.S.C.", exchange: "ADX", sector: "Industrial" },
  { symbol: "GIH", yahooSymbol: "GIH.AE", name: "Gulf Investment House - KPSC", exchange: "ADX", sector: "Financial Services" },
  { symbol: "ALPHADATA", yahooSymbol: "ALPHADATA.AE", name: "Alpha Data PJSC", exchange: "ADX", sector: "Technology" },
  { symbol: "NCTH", yahooSymbol: "NCTH.AE", name: "National Corporation for Tourism and Hotels", exchange: "ADX", sector: "Hospitality" },
  { symbol: "SUDATEL", yahooSymbol: "SUDATEL.AE", name: "Sudatel Telecom Group Limited", exchange: "ADX", sector: "Telecom" },
  { symbol: "SAWAEED", yahooSymbol: "SAWAEED.AE", name: "Sawaeed Holding P.J.S.C.", exchange: "ADX", sector: "Industrial" },
  { symbol: "HH", yahooSymbol: "HH.AE", name: "Hily Holding PJSC", exchange: "ADX", sector: "Conglomerates" },
  { symbol: "IH", yahooSymbol: "IH.AE", name: "Insurance House - P J S C", exchange: "ADX", sector: "Insurance" },
  { symbol: "AFNIC", yahooSymbol: "AFNIC.AE", name: "Al Fujairah National Insurance Company P.J.S.C", exchange: "ADX", sector: "Insurance" },
  { symbol: "FIDELITYUNITED", yahooSymbol: "FIDELITYUNITED.AE", name: "United Fidelity Insurance Company (P.S.C.)", exchange: "ADX", sector: "Insurance" },
  { symbol: "RAPCO", yahooSymbol: "RAPCO.AE", name: "RAPCO Investment PJSC", exchange: "ADX", sector: "Investment" },
  { symbol: "TNI", yahooSymbol: "TNI.AE", name: "The National Investor Pr. J.S.C.", exchange: "ADX", sector: "Financial Services" },
  { symbol: "KICO", yahooSymbol: "KICO.AE", name: "Al Khaleej Investment P.J.S.C.", exchange: "ADX", sector: "Investment" },
  { symbol: "RAKWCT", yahooSymbol: "RAKWCT.AE", name: "Ras Al Khaimah Co. for White Cement & Construction Materials P.S.C.", exchange: "ADX", sector: "Industrial" },
  { symbol: "OEIHC", yahooSymbol: "OEIHC.AE", name: "Oman & Emirates Investment Holding Company SAOG", exchange: "ADX", sector: "Investment" },
  { symbol: "AKIC", yahooSymbol: "AKIC.AE", name: "Al Khazna Insurance Company P.S.C.", exchange: "ADX", sector: "Insurance" },
];

export const DFM_STOCKS: StockInfo[] = [
  { symbol: "EMIRATESNBD", yahooSymbol: "EMIRATESNBD.AE", name: "Emirates NBD Bank PJSC", exchange: "DFM", sector: "Banking" },
  { symbol: "DEWA", yahooSymbol: "DEWA.AE", name: "Dubai Electricity and Water Authority (PJSC)", exchange: "DFM", sector: "Utilities" },
  { symbol: "EMAAR", yahooSymbol: "EMAAR.AE", name: "Emaar Properties PJSC", exchange: "DFM", sector: "Real Estate" },
  { symbol: "EMAARDEV", yahooSymbol: "EMAARDEV.AE", name: "Emaar Development PJSC", exchange: "DFM", sector: "Real Estate" },
  { symbol: "DIB", yahooSymbol: "DIB.AE", name: "Dubai Islamic Bank P.J.S.C.", exchange: "DFM", sector: "Banking" },
  { symbol: "DU", yahooSymbol: "DU.AE", name: "Emirates Integrated Telecommunications Company PJSC", exchange: "DFM", sector: "Telecom" },
  { symbol: "SALIK", yahooSymbol: "SALIK.AE", name: "Salik Company P.J.S.C.", exchange: "DFM", sector: "Technology" },
  { symbol: "MASQ", yahooSymbol: "MASQ.AE", name: "Mashreqbank PSC", exchange: "DFM", sector: "Banking" },
  { symbol: "CBD", yahooSymbol: "CBD.AE", name: "Commercial Bank of Dubai PSC", exchange: "DFM", sector: "Banking" },
  { symbol: "AIRARABIA", yahooSymbol: "AIRARABIA.AE", name: "Air Arabia PJSC", exchange: "DFM", sector: "Aviation" },
  { symbol: "TECOM", yahooSymbol: "TECOM.AE", name: "TECOM Group PJSC", exchange: "DFM", sector: "Real Estate" },
  { symbol: "EMPOWER", yahooSymbol: "EMPOWER.AE", name: "Emirates Central Cooling Systems Corporation", exchange: "DFM", sector: "Utilities" },
  { symbol: "DIC", yahooSymbol: "DIC.AE", name: "Dubai Investments PJSC", exchange: "DFM", sector: "Conglomerates" },
  { symbol: "TALABAT", yahooSymbol: "TALABAT.AE", name: "Talabat Holding plc", exchange: "DFM", sector: "Technology" },
  { symbol: "PARKIN", yahooSymbol: "PARKIN.AE", name: "Parkin Company P.J.S.C.", exchange: "DFM", sector: "Services" },
  { symbol: "DFM", yahooSymbol: "DFM.AE", name: "Dubai Financial Market P.J.S.C.", exchange: "DFM", sector: "Financial Services" },
  { symbol: "TABREED", yahooSymbol: "TABREED.AE", name: "National Central Cooling Company PJSC", exchange: "DFM", sector: "Utilities" },
  { symbol: "GFH", yahooSymbol: "GFH.AE", name: "GFH Financial Group BSC", exchange: "DFM", sector: "Financial Services" },
  { symbol: "ALANSARI", yahooSymbol: "ALANSARI.AE", name: "Al Ansari Financial Services PJSC", exchange: "DFM", sector: "Financial Services" },
  { symbol: "DTC", yahooSymbol: "DTC.AE", name: "Dubai Taxi Company P.J.S.C.", exchange: "DFM", sector: "Transport" },
  { symbol: "SPINNEYS", yahooSymbol: "SPINNEYS.AE", name: "Spinneys 1961 Holding plc", exchange: "DFM", sector: "Consumer Staples" },
  { symbol: "AJMANBANK", yahooSymbol: "AJMANBANK.AE", name: "Ajman Bank PJSC", exchange: "DFM", sector: "Banking" },
  { symbol: "DEYAAR", yahooSymbol: "DEYAAR.AE", name: "Deyaar Development PJSC", exchange: "DFM", sector: "Real Estate" },
  { symbol: "TAALEEM", yahooSymbol: "TAALEEM.AE", name: "Taaleem Holdings PJSC", exchange: "DFM", sector: "Education" },
  { symbol: "UPP", yahooSymbol: "UPP.AE", name: "Union Properties Public Joint Stock Company", exchange: "DFM", sector: "Real Estate" },
  { symbol: "AMANAT", yahooSymbol: "AMANAT.AE", name: "Amanat Holdings PJSC", exchange: "DFM", sector: "Investment" },
  { symbol: "ARMX", yahooSymbol: "ARMX.AE", name: "Aramex PJSC", exchange: "DFM", sector: "Logistics" },
  { symbol: "SUKOONTAKAFL", yahooSymbol: "SUKOONTAKAFL.AE", name: "Sukoon Takaful PJSC", exchange: "DFM", sector: "Insurance" },
  { symbol: "AMLAK", yahooSymbol: "AMLAK.AE", name: "Amlak Finance PJSC", exchange: "DFM", sector: "Financial Services" },
  { symbol: "DRC", yahooSymbol: "DRC.AE", name: "Dubai Refreshment (P.J.S.C.)", exchange: "DFM", sector: "Consumer Staples" },
  { symbol: "NCC", yahooSymbol: "NCC.AE", name: "National Cement Company (Public Shareholding Co.)", exchange: "DFM", sector: "Industrial" },
  { symbol: "ALRAMZ", yahooSymbol: "ALRAMZ.AE", name: "Al Ramz Corporation Investment and Development P.J.S.C.", exchange: "DFM", sector: "Financial Services" },
  { symbol: "SHUAA", yahooSymbol: "SHUAA.AE", name: "SHUAA Capital PSC", exchange: "DFM", sector: "Financial Services" },
  { symbol: "DSI", yahooSymbol: "DSI.AE", name: "Drake and Scull International P.J.S.C.", exchange: "DFM", sector: "Construction" },
  { symbol: "SALAMA", yahooSymbol: "SALAMA.AE", name: "Islamic Arab Insurance Co. (Salama) PJSC", exchange: "DFM", sector: "Insurance" },
  { symbol: "GULFNAV", yahooSymbol: "GULFNAV.AE", name: "Gulf Navigation Holding PJSC", exchange: "DFM", sector: "Transport" },
  { symbol: "DUBAIRESI", yahooSymbol: "DUBAIRESI.AE", name: "Dubai Residential REIT", exchange: "DFM", sector: "Real Estate" },
  { symbol: "AMAN", yahooSymbol: "AMAN.AE", name: "Dubai Islamic Insurance & Reinsurance Co. (Aman) (P.J.S.C)", exchange: "DFM", sector: "Insurance" },
  { symbol: "ALEC", yahooSymbol: "ALEC.AE", name: "ALEC Holdings PJSC", exchange: "DFM", sector: "Construction" },
  { symbol: "UNIONCOOP", yahooSymbol: "UNIONCOOP.AE", name: "Union Coop", exchange: "DFM", sector: "Consumer Staples" },
  { symbol: "NIND", yahooSymbol: "NIND.AE", name: "National Industries Group Holding", exchange: "DFM", sector: "Industrial" },
  { symbol: "SALAM_BAH", yahooSymbol: "SALAM_BAH.AE", name: "Al Salam Bank Bahrain B.S.C.", exchange: "DFM", sector: "Banking" },
  { symbol: "MKHZN", yahooSymbol: "MKHZN.AE", name: "National Storage Affiliates Trust", exchange: "DFM", sector: "Real Estate" },
  { symbol: "IFA", yahooSymbol: "IFA.AE", name: "International Financial Advisors KCSC", exchange: "DFM", sector: "Financial Services" },
  { symbol: "DIN", yahooSymbol: "DIN.AE", name: "Deyaar Investment PJSC", exchange: "DFM", sector: "Real Estate" },
  { symbol: "NGI", yahooSymbol: "NGI.AE", name: "National General Insurance PJSC", exchange: "DFM", sector: "Insurance" },
  { symbol: "EIBANK", yahooSymbol: "EIBANK.AE", name: "Emirates Investment Bank PJSC", exchange: "DFM", sector: "Banking" },
  { symbol: "ITHMR", yahooSymbol: "ITHMR.AE", name: "Ithmaar Holding B.S.C.", exchange: "DFM", sector: "Banking" },
  { symbol: "AMCREIT", yahooSymbol: "AMCREIT.AE", name: "Emirates REIT (CEIC) Limited", exchange: "DFM", sector: "Real Estate" },
  { symbol: "NIH", yahooSymbol: "NIH.AE", name: "National International Holding", exchange: "DFM", sector: "Conglomerates" },
  { symbol: "UFC", yahooSymbol: "UFC.AE", name: "United Foods Company (P.S.C.)", exchange: "DFM", sector: "Consumer Staples" },
  { symbol: "TAKAFUL-EM", yahooSymbol: "TAKAFUL-EM.AE", name: "Takaful Emarat Insurance PSC", exchange: "DFM", sector: "Insurance" },
  { symbol: "UNIKAI", yahooSymbol: "UNIKAI.AE", name: "Unikai Foods P.L.C.", exchange: "DFM", sector: "Consumer Staples" },
  { symbol: "BHMCAPITAL", yahooSymbol: "BHMCAPITAL.AE", name: "BHM Capital Financial Services PJSC", exchange: "DFM", sector: "Financial Services" },
  { symbol: "ALFIRDOUS", yahooSymbol: "ALFIRDOUS.AE", name: "Al Firdous Holdings PJSC", exchange: "DFM", sector: "Real Estate" },
  { symbol: "WATANIA", yahooSymbol: "WATANIA.AE", name: "Watania International Holding PJSC", exchange: "DFM", sector: "Insurance" },
  { symbol: "EKTTITAB", yahooSymbol: "EKTTITAB.AE", name: "Ekttitab Holding Company KSCC", exchange: "DFM", sector: "Financial Services" },
  { symbol: "ERC", yahooSymbol: "ERC.AE", name: "Emirates Refreshments Company P.J.S.C.", exchange: "DFM", sector: "Consumer Staples" },
  { symbol: "ALSALAMSUDAN", yahooSymbol: "ALSALAMSUDAN.AE", name: "Al Salam Bank Sudan", exchange: "DFM", sector: "Banking" },
];

export const ALL_STOCKS: StockInfo[] = [...ADX_STOCKS, ...DFM_STOCKS];

export const SECTORS = [
  "Banking", "Real Estate", "Energy", "Telecom", "Insurance", "Conglomerates",
  "Industrial", "Healthcare", "Technology", "Financial Services", "Utilities",
  "Consumer Staples", "Consumer Services", "Aviation", "Logistics", "Construction",
  "Hospitality", "Services", "Investment", "Chemicals", "Transport", "Education",
];
